// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SieteYMediaBack.Models
{
    [Table("CardGame")]
    public partial class CardGame
    {
        [Key]
        [Column(TypeName = "numeric(18, 0)")]
        public decimal IdGame { get; set; }
        [StringLength(50)]
        public string Winner { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? points { get; set; }
    }
}