// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SieteYMediaBack.Models
{
    public partial class Player
    {
        [Key]
        [Column(TypeName = "numeric(18, 0)")]
        public decimal IdPlayer { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
    }
}