// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SieteYMediaBack.Models
{
    public partial class SieteYMediaContext : DbContext
    {
        public SieteYMediaContext()
        {
        }

        public SieteYMediaContext(DbContextOptions<SieteYMediaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CardGame> CardGames { get; set; }
        public virtual DbSet<Player> Players { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CardGame>(entity =>
            {
                entity.Property(e => e.IdGame).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<Player>(entity =>
            {
                entity.Property(e => e.IdPlayer).ValueGeneratedOnAdd();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}